name: root
channels:
  - defaults
  - cantera
  - conda-forge
dependencies:
  - numpy 
  - cantera 
  - matplotlib 
  - scipy
  - seaborn
  - bokeh
  - pandas
  - alembic
  - asn1crypto
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - conda
  - conda-env
  - configurable-http-proxy
  - cryptography
  - decorator
  - entrypoints
  - gmp
  - html5lib
  - idna
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterhub==0.8
  - jupyterlab
  - jupyterlab_launcher
  - libffi
  - libsodium
  - mako
  - markupsafe
  - mistune
  - nbconvert
  - nbformat
  - ncurses
  - nodejs
  - notebook
  - nbgrader
  - openssl
  - packaging
  - pamela
  - pandoc
  - pandocfilters
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - ptyprocess
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python=3.6.2=0
  - python-dateutil
  - python-editor
  - python-oauth2
  - pyzmq
  - readline
  - requests
  - ruamel_yaml
  - setuptools
  - simplegeneric
  - six
  - sqlalchemy
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - libgcc
  - pip:
    - ipython-genutils
    - jupyter-client
    - jupyter-core
    - jupyterlab-launcher
    - prompt-toolkit
    - ruamel-yaml

